# Sección 2 - Estructuras de datos

![Estructuras pandas](https://drive.google.com/uc?id=1Jund4qF0oJ2DMc-cg5N5tU_9jQRwsCXZ)

En esta sección vamos a conocer las estructuras principales de datos existentes en pandas, como son las **Series y los DataFrames.** 

Además, trabajaremos con tipos de datos peculiares como pueden ser los timeseries o los timedelta. 

También aprenderemos a leer y escribir datos con pandas.  


Para cada uno de los ejercicios, utilizaremos un directorio llamado ./data que contendrá todos los archivos necesarios.

**Sugerencia:** Para no tener que cambiar rutas, te recomiendo trabajar de manera local y colocar la carpeta data en el mismo directorio en el que planeas trabajar con los cuadernos de esta sección.

## Qué estudiaremos en este Notebook


1. **Series**
    * Usando Arrays Numpy.
    * Usando Diccionarios.  


2. **DataFrame**
    * Desde Diccionario de Series.
    * Desde Diccionario de Valores.
    * Desde Lista de Diccionarios.
    * Desde Lista de Listas.
    * Usando Numpy
    * Operaciones Básicas sobre DataFrame
        * Info
        * Head
        * Column


3. **Lectura y Escritura.**
    * **Lectura**
    	* Read_csv  - Ficheros csv
        * Read_json - Ficheros .JSON
        * Read_fwf  - Ficheros de texto Plano
        * Read_parquet - Ficheros .parquet 
        
    * **Escritura**
        * to_csv 
        * to_json
        * to_parquet
        

4. **Indexado y Selección de Datos - Parte I**

    * Selección por Etiqueta

    * Loc - Selección por ïndice del DataFrame
    
	* Slicig
    
	* Consulta por columnas
    
	* Consulta por filas y columnas

    * Iloc Selección por Posición
    

5. **Indexado y Selección de Datos - Parte II**

    * Sample - Recuperación aleatoria de filas

    * Isin   - Valores incluidos

    * Where  - Filtrando Datos	

    * Query  - Selección mediante expresiones

    * Drop_Duplicates - Borrando duplicados
    

6. **Multi-Index**

7. **Timeseries y Timestamp**

8. **Timedelta**

9. **Ejercicios**

---
## Lección 1 - Series

La Serie es realmente una matriz unidimensional que puede contener cualquier tipo de datos (enteros, cadenas, floats, objetos de Python, etc.). La serie también posee un índice. Dispone de varios tipos de constructores.

In [1]:
import pandas as pd
import numpy as np

---
### 1. Usando un numpy array

In [2]:
valores = np.array([1,2,3,4,5])
serie = pd.Series(valores)
serie

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [3]:
serie.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
serie = pd.Series(valores, index = ['a','b','c','d','e'])
serie

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [5]:
serie.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

---
### 2. Usando un diccionario python

In [6]:
d = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
#ahora creamos la serie utilizando el diccionario creado

Si usamos el diccionario, y además especificamos un indice, los valores se ordenan según el indice ordenado

In [7]:
serie = pd.Series(d, index = ['b','c','a','e','d'])
serie

b    2
c    3
a    1
e    5
d    4
dtype: int64

La serie actúa de manera muy similar a un numpy array y es un argumento válido para la mayoría de las funciones NumPy.

In [8]:
np.sum(serie)

15

In [9]:
np.max(serie)

5

Podemos consultar los valores especificando un valor del indice. También podemos consultar el tipo de la serie con *dtype* y convertirlo a un numpy array con la función *to_numpy()*

In [10]:
serie

b    2
c    3
a    1
e    5
d    4
dtype: int64

In [11]:
serie[0]

2

In [12]:
serie.dtype

dtype('int64')

In [13]:
array = serie.to_numpy()
print(type(array))
array

<class 'numpy.ndarray'>

array([2, 3, 1, 5, 4], dtype=int64)

<div class="alert alert-warning">También podemos interpretar el tipo Serie de pandas como un diccionario python, de manera que podemos tanto consultar, como añadir nuevos pares clave-valor a la misma.</div>

In [14]:
serie

b    2
c    3
a    1
e    5
d    4
dtype: int64

In [15]:
serie['e']

5

In [16]:
serie['f'] = 6
serie

b    2
c    3
a    1
e    5
d    4
f    6
dtype: int64

In [17]:
'e' in serie

True

In [18]:
'h' in serie

False

Y como diccionario que se puede considerar, podemos pedir sus claves y sus valores

In [19]:
serie.keys()

Index(['b', 'c', 'a', 'e', 'd', 'f'], dtype='object')

In [20]:
serie.values

array([2, 3, 1, 5, 4, 6], dtype=int64)

<div class="alert alert-warning">Cuando hemos trabajado con matrices NumPy, normalmente no era necesario recorrer valor a valor la misma para aplicar una operación. Lo mismo ocurre cuando se trabaja con Series en pandas.</div>

In [21]:
serie

b    2
c    3
a    1
e    5
d    4
f    6
dtype: int64

In [22]:
serie * 2

b     4
c     6
a     2
e    10
d     8
f    12
dtype: int64

In [23]:
serie2 = pd.Series(np.random.randint(0,10,6), index = ['b', 'c', 'a', 'e', 'd', 'f'])
serie2

b    8
c    6
a    2
e    0
d    7
f    2
dtype: int32

In [24]:
print(f"Vamos a sumar serie:\n{serie} y serie2:\n{serie2}")
print(f"La suma es:\n{serie + serie2}")

Vamos a sumar serie:
b    2
c    3
a    1
e    5
d    4
f    6
dtype: int64 y serie2:
b    8
c    6
a    2
e    0
d    7
f    2
dtype: int32
La suma es:
b    10
c     9
a     3
e     5
d    11
f     8
dtype: int64

**Si algun indice no coincide, se almacena un NaN**

In [25]:
serie2['g'] = 10

In [26]:
serie

b    2
c    3
a    1
e    5
d    4
f    6
dtype: int64

In [27]:
serie2

b     8
c     6
a     2
e     0
d     7
f     2
g    10
dtype: int32

In [28]:
serie + serie2

a     3.0
b    10.0
c     9.0
d    11.0
e     5.0
f     8.0
g     NaN
dtype: float64

## Lección 2 - DataFrame

Los DataFrame son una **estructura de datos bidimensional** que admite columnas de diferentes tipos. Podemos entenderlos como una tabla SQL, en el sentido de estar **formado por filas y columnas.** 

**Generalmente es el objeto de pandas más utilizado.** Al igual que Series, DataFrame acepta muchos tipos diferentes de entrada.

La forma de usarlo es la siguiente:

**<div class="alert alert-info"> pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None) </div>**

**Parametros:**

* **data:** Datos a convertir a DataFrame. Puede contener series, matrices, constantes, clases de datos u objetos similares a listas.


* **index:** Índice usado para el DataFrame resultante. Si no se indica nada, tomará un valor númerico por defecto (empezando en el 0).


* **columns:** Etiquetas de columna que se usarán para el dataframe resultante cuando los datos no las tengan, con el valor predeterminado RangeIndex(0, 1, 2, …, n). 


* **dtype:** Tipo de dato a forzar. Solo se permite un único tipo de datos. Por defecto viene a None.


* **copy:**  Para indicarle si queremos hacer una copia de los datos introducidos en el parámetro data. Por defecto viene a None lo que equivale a True. Por tanto por defecto se hacen una copia de los datos de entrada.

**Vamos a ver distintos ejemplos de uso.**

---
### 1. Construyendo un DataFramen desde un diccionario de series

In [29]:
import numpy as np
import pandas as pd

In [30]:
d = {'col1': pd.Series([1., 2., 3., 4.]),
     'col2': pd.Series([4., 3., 2., 1.])}

df = pd.DataFrame(d)
df

   col1  col2
0   1.0   4.0
1   2.0   3.0
2   3.0   2.0
3   4.0   1.0

---
### 2. Construyendo un DataFramen desde un diccionario de valores

In [31]:
d = {'col1': [1., 2., 3., 4.],
     'col2': [4., 3., 2., 1.]}

df = pd.DataFrame(d, index = ['a','b','c','e'])#con indice
df

   col1  col2
a   1.0   4.0
b   2.0   3.0
c   3.0   2.0
e   4.0   1.0

In [32]:
d = {'col1': [1., 2., 3., 4.],
     'col2': [4., 3., 2., 1.]}

df = pd.DataFrame(d)#sin indice, vemos que le pone por defecto un valor numérico
print(df.dtypes)
df

col1    float64
col2    float64
dtype: object

   col1  col2
0   1.0   4.0
1   2.0   3.0
2   3.0   2.0
3   4.0   1.0

In [33]:
df2 = pd.DataFrame(data=d, dtype=np.int8)
print(df2.dtypes)
df2

col1    int8
col2    int8
dtype: object

   col1  col2
0     1     4
1     2     3
2     3     2
3     4     1

---
### 3. Usando una lista de diccionarios

In [34]:
l = [{'col1': 1, 'col2' : 4}, {'col1': 2, 'col2' : 3},  
     {'col1': 3, 'col2' : 2}, {'col1': 4, 'col2' : 1, 'col3' : 3}]

df = pd.DataFrame(l, index = ['a','b','c','e'])
df

   col1  col2  col3
a     1     4   NaN
b     2     3   NaN
c     3     2   NaN
e     4     1   3.0

Como podéis observar, los dataframes están formados por un conjunto de series. Por ello, poseen una características muy similares a ellas, y podemos consultarlos o modificarlos de la misma manera.

**Recuperando valores de una columna**

In [35]:
# Recupero la columna con []
df['col2']

a    4
b    3
c    2
e    1
Name: col2, dtype: int64

In [36]:
type(df['col2'])

pandas.core.series.Series

**Creando columnas nuevas**

In [37]:
#Como si fuese un diccionario. Indico la clave nueva y le paso los valores.
df['col4'] = df['col1'] + df['col2']
df

   col1  col2  col3  col4
a     1     4   NaN     5
b     2     3   NaN     5
c     3     2   NaN     5
e     4     1   3.0     5

In [38]:
#usando el método Insert, le paso la posición donde quiero la columna, nombre y valorES.
#df.inser(posicion, nombre_nueva_columna, valorES)
df.insert(0, 'col0', df['col4'] + df['col2'])
df

   col0  col1  col2  col3  col4
a     9     1     4   NaN     5
b     8     2     3   NaN     5
c     7     3     2   NaN     5
e     6     4     1   3.0     5

El método *assign*, nos permite **crear una nueva columna en el dataframe, la añade al final**

In [39]:
df = df.assign(col5 = 3)#si quisieramos valores espeficicos para cada fila, hay que pasarlos en una lista [3, 4, 5, 6]
df

   col0  col1  col2  col3  col4  col5
a     9     1     4   NaN     5     3
b     8     2     3   NaN     5     3
c     7     3     2   NaN     5     3
e     6     4     1   3.0     5     3

**Eliminar columnas**

In [40]:
# Elimino columnas con del
del df['col3']
df

   col0  col1  col2  col4  col5
a     9     1     4     5     3
b     8     2     3     5     3
c     7     3     2     5     3
e     6     4     1     5     3

### 4. Usando listas de listas.

También podemos crear un DataFrame a partir de una lista de listas.

Veamos un ejemplo con datos de redes sociales

In [41]:
face = ['Facebook', 5432, True, 2006]
yotu = ['Youtube', 432, False, 2007]
wsp  = ['WhatsApp', 1500, True, 2009]
lkn  = ['LinkedIn', 432, False, 2003]
ig   = ['Instagram', 1000, True, 2010]
twt  = ['Twitter', 229, False, 2006]

In [42]:
lista_rrss = [face, yotu, wsp, lkn, ig, twt]
lista_rrss

[['Facebook', 5432, True, 2006],
 ['Youtube', 432, False, 2007],
 ['WhatsApp', 1500, True, 2009],
 ['LinkedIn', 432, False, 2003],
 ['Instagram', 1000, True, 2010],
 ['Twitter', 229, False, 2006]]

In [43]:
#creamos el DataFrame
df_rrss = pd.DataFrame(lista_rrss, columns=['Nombre_RS', 'Cantidad_Usuarios', 'Propiedad_Facebook', 'Año_Creación'])
df_rrss

   Nombre_RS  Cantidad_Usuarios  Propiedad_Facebook  Año_Creación
0   Facebook               5432                True          2006
1    Youtube                432               False          2007
2   WhatsApp               1500                True          2009
3   LinkedIn                432               False          2003
4  Instagram               1000                True          2010
5    Twitter                229               False          2006

### 5. Usando NumPy

In [44]:
df1 = pd.DataFrame(np.random.randint(0,10,6).reshape(2,3))
df1

   0  1  2
0  4  3  5
1  9  1  7

In [45]:
df2 = pd.DataFrame(np.random.randint(0,10,6), index = ['b', 'c', 'a', 'e', 'd', 'f'], columns=['Valor'])
df2

   Valor
b      7
c      4
a      0
e      1
d      0
f      2

In [46]:
data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
                dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df3 = pd.DataFrame(data, columns=['c', 'a', 'b'])

df3

   c  a  b
0  3  1  2
1  6  4  5
2  9  7  8

### 6. Operaciones Básicas sobre DataFrames.

Vamos a ver algunas de las operaciones más básicas que podemos realizar sobre DataFrames.

* Método para obtener información del DataFrame __<code>.info()</code>__
* Método para obtener las primeras filas de un dataframe con __<code>.head()</code>__
* Atributo para ver los nombres de las columnas de un dataframe con __<code>.columns</code>__

In [47]:
df_rrss.info

<bound method DataFrame.info of    Nombre_RS  Cantidad_Usuarios  Propiedad_Facebook  Año_Creación
0   Facebook               5432                True          2006
1    Youtube                432               False          2007
2   WhatsApp               1500                True          2009
3   LinkedIn                432               False          2003
4  Instagram               1000                True          2010
5    Twitter                229               False          2006>

In [48]:
df_rrss.head()

   Nombre_RS  Cantidad_Usuarios  Propiedad_Facebook  Año_Creación
0   Facebook               5432                True          2006
1    Youtube                432               False          2007
2   WhatsApp               1500                True          2009
3   LinkedIn                432               False          2003
4  Instagram               1000                True          2010

In [49]:
df_rrss.columns

Index(['Nombre_RS', 'Cantidad_Usuarios', 'Propiedad_Facebook', 'Año_Creación'], dtype='object')

---
## Leccion 3 - Lectura y escritura

Cuando trabajamos con pandas, es habitual que tengamos que l**eer un fichero de datos, bien sea en formato CSV, JSON, o similar.** 

Luego, una vez tenemos los resultados deseados, solemos **volcar esos resultados a un fichero.**

**<div class="alert alert-success">Pandas nos proporciona una serie de métodos de entrada / salida para estos fines.</div>**

In [50]:
import numpy as np
import pandas as pd

In [51]:
from pathlib import Path
data_path = Path('./data')
print(data_path)

data

---
## 1. Lectura

Antes de usar cualquier método para la lectura de los ficheros, **es muy recomendable mirar la estructura que tiene el fichero que queremos leer. Nos ayudará a obtener de manera adecuada los datos.**

Debemos fijarnos en los separadores(normalmente se usa la coma, pero pueden usarse otros como ; /t), en como se organizan los datos, si hay cabecera o no, el tamaño del fichero, columnas que vamos a usar, formato de los datos.

Tras este vistazo, podemos proceder a la lectura.

---
### 1.1 read_csv

In [52]:
dataset = pd.read_csv(data_path / 'dataset.csv', sep = ',')#por defecto el separador que utiliza el método read es la coma.
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [53]:
#leemos solo las columnas que vamos a usar
pd.read_csv(data_path / 'dataset.csv', sep = ',', usecols=['Gender','Age']).head()

  Gender  Age
0   Male   41
1   Male   54
2   Male   42
3   Male   40
4   Male   46

---
### 1.2 read_json

Para este tipo de ficheros se hace **más importante realizar el visionado previo antes de cargar los datos en python.** Ya que pueden requerir distintas orientaciones para obtener bien los datos. Podemos ver las distintas opciones que permite el párametro orient en la documentación [oficial](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)

In [54]:
#los datos estan organizados por indice
ds = pd.read_json(data_path / 'dataset_index.json', orient='index')
ds.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

In [55]:
#los datos están como:
#columna1:valor, columna2:valor...
ds = pd.read_json(data_path / 'dataset_records.json', orient='records')
ds.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

In [56]:
#en este caso, el fichero, tiene los datos partidos:
# primero tiene el indice
#luego las columnas
#luego los datos.
#tenemos que fijarnos siempre en como están organizados los ficheros para usar la orientación adecuada.
ds = pd.read_json(data_path / 'df_to_write.json', orient='split')
ds.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

---
### 1.3 read_fwf

Lee un fichero de texto plano. Es mucho más liviano pero puede haber muchos errores con la carga de datos.

In [57]:
widths = [1, 6, 4, 2, 7, 2]#lista con los tamaños de cada campo
ds_fijo = pd.read_fwf(data_path / 'dataset_fijo', widths=widths, header = None)
ds_fijo.columns = ['Number', 'City', 'Gender', 'Age', 'Income', 'Illness']#le pasamos los nombres de las columnas
ds_fijo

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

---
### 1.4 read_parquet

El formato Parquet es un formato open-source de almacenamiento en columnas para Hadoop.

Fue creado para poder disponer de un formato libre de compresión y codificación eficiente.

In [58]:
print(data_path)

data

In [59]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\saul lázaro hermoso\anaconda3\lib\site-packages (11.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\saul lázaro hermoso\anaconda3\lib\site-packages (from pyarrow) (1.24.3)

In [ ]:
#!pip install pyarrow si da error al cargar
ds_parquet = pd.read_parquet(data_path / 'dataset.parquet', engine='pyarrow')
print(ds_parquet.shape)
ds_parquet.head()

Fijaros como el fichero en formato parquet ocupa 1.7 MB mientras que en CSV ocupa 5.7 MB

### 1.5 read_excel

In [60]:
df_excel = pd.read_excel(data_path / 'df_to_write.xlsx')
df_excel.shape

(100, 6)

In [61]:
df_excel.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

Podemos ver los parámetros de un método poniendo el simbolo ? tras el nombre del método, no debemos poner nada más en esa celda.

In [62]:
pd.read_excel?

---
## 2. Escritura

In [63]:
#leemos las 100 primeras filas del dataset para hacer pruebas de escritura.
df_to_write = dataset.head(100)
df_to_write.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

### 2.1 to_csv

In [64]:
df_to_write.to_csv(data_path / 'df_to_write.csv', index = False, sep = '#', header = False)

In [ ]:
#prueba a leer el nuevo fichero creado.

### 2.2 to_json

In [65]:
df_to_write.to_json(data_path / 'df_to_write.json', orient = 'split')

### 2.3 to_parquet

In [66]:
df_to_write.to_parquet(data_path / 'df_to_write.parquet')

Apache Parquet proporciona una serialización binaria particionada en columnas para los dataframes. Está diseñado para hacer que la lectura y escritura de los DF sea eficiente.

Para poder escribir en formato parquet, necesitamos instalar la dependencia *pyarrow*.

### 2.4 to_excel

In [67]:
df_to_write.to_excel(data_path / 'df_to_write.xlsx', index=False)#para no guardar el indice.

In [69]:
df_to_write.to_excel?

---
## Lección 4 - Indexado y selección de datos - Parte I

En esta lección vamos a aprender como consultar datos en pandas, tanto en Series como en DataFrames. Los datos en pandas están indexados, esto es, poseen un indice el cual podemos usar para **incrementar la eficiencia nuestras consultas.**

In [68]:
import numpy as np
import pandas as pd

from pathlib import Path
data_path = Path('./data')

In [69]:
dataset = pd.read_csv(data_path / 'dataset.csv', sep = ',')
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

---
### 1. Seleccion por Etiqueta

Simplemente hay que poner entre corchetes el nombre de las columnas que queremos seleccionar.

In [71]:
dataset['City']

0         Dallas
1         Dallas
2         Dallas
3         Dallas
4         Dallas
           ...
149995    Austin
149996    Austin
149997    Austin
149998    Austin
149999    Austin
Name: City, Length: 150000, dtype: object

In [72]:
dataset[['City', 'Income']].head()

     City   Income
0  Dallas  40367.0
1  Dallas  45084.0
2  Dallas  52483.0
3  Dallas  40941.0
4  Dallas  50289.0

In [73]:
dataset['City'].value_counts()#contar el número de apariciones de cada valor de la columna City

City
New York City      50307
Los Angeles        32173
Dallas             19707
Mountain View      14219
Austin             12292
Boston              8301
Washington D.C.     8120
San Diego           4881
Name: count, dtype: int64

In [74]:
#tamnbién podemos guardar en una variable las columnas que queremos.
target = ['City', 'Income']
dataset[target]

          City    Income
0       Dallas   40367.0
1       Dallas   45084.0
2       Dallas   52483.0
3       Dallas   40941.0
4       Dallas   50289.0
...        ...       ...
149995  Austin   93669.0
149996  Austin   96748.0
149997  Austin  111885.0
149998  Austin  111878.0
149999  Austin   87251.0

[150000 rows x 2 columns]

**Otra forma de acceder a las columnas de un dataframe es:**

* nombre_df.__nombre_columna__ (sin las comillas de string)

In [75]:
dataset.City.value_counts()

City
New York City      50307
Los Angeles        32173
Dallas             19707
Mountain View      14219
Austin             12292
Boston              8301
Washington D.C.     8120
San Diego           4881
Name: count, dtype: int64

In [76]:
dataset.Gender.value_counts()

Gender
Male      83800
Female    66200
Name: count, dtype: int64

**También podemos seleccionar columnas empleando condiciones**

Si realizamos la siguiente comparación, obtenemos una serie pandas de True y False.

In [77]:
dataset['City'] == 'Dallas'

0          True
1          True
2          True
3          True
4          True
          ...
149995    False
149996    False
149997    False
149998    False
149999    False
Name: City, Length: 150000, dtype: bool

Esa serie de booleanos, se puede pasar al DF, para realizar el filtro.

In [78]:
#vamos a ver como podemos quedarnos solo con los registros que cumplan una determinada condición
dallas_city = dataset[dataset['City'] == 'Dallas']

print(f"Número de registros con nombre:{dallas_city['City'].value_counts()}")
#print(len(dallas_city))#lo podemos hacer también con la función len.
dallas_city

Número de registros con nombre:City
Dallas    19707
Name: count, dtype: int64

       Number    City  Gender  Age   Income Illness
0           1  Dallas    Male   41  40367.0      No
1           2  Dallas    Male   54  45084.0      No
2           3  Dallas    Male   42  52483.0      No
3           4  Dallas    Male   40  40941.0      No
4           5  Dallas    Male   46  50289.0      No
...       ...     ...     ...  ...      ...     ...
19702   19703  Dallas  Female   59  30021.0      No
19703   19704  Dallas    Male   33  34643.0      No
19704   19705  Dallas    Male   33  53190.0      No
19705   19706  Dallas    Male   37  54265.0      No
19706   19707  Dallas    Male   59  51265.0      No

[19707 rows x 6 columns]

In [79]:
# o podemos hacerlo guardando la condición en una variable como haciamos en numpy con las matrices.
dallas = dataset['City'] == 'Dallas'
dallas_city = dataset[dallas]
dallas_city['City'].value_counts()

City
Dallas    19707
Name: count, dtype: int64

**También podemos combinar varias condiciones**

In [80]:
dallas_female = dataset[(dataset['City'] == 'Dallas') & (dataset['Gender'] == 'Female')]
dallas_female['Gender'].value_counts()

Gender
Female    8705
Name: count, dtype: int64

---
### 2. loc - Selección por Indice del DataFrame

**<conde>loc</conde>** se basa principalmente en consultar según el <font color='red'>**valor del indice del Dataframe.** </font>

* Inicialmente, el indice va desde **0 a len(dataset)-1.** 

* Pero si modificamos el valor del indice, podemos consultarlo por dicho valor.

Veamos un ejemplo.

In [81]:
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [82]:
dataset.loc[1]

Number           2
City        Dallas
Gender        Male
Age             54
Income     45084.0
Illness         No
Name: 1, dtype: object

In [83]:
#vamos a probar a modificar el índice para probar que efectivamente accedemos por el valor del indice del DataFrame.
dataset1 = dataset.set_index(np.arange(10, len(dataset)+10))
dataset1.head()

    Number    City Gender  Age   Income Illness
10       1  Dallas   Male   41  40367.0      No
11       2  Dallas   Male   54  45084.0      No
12       3  Dallas   Male   42  52483.0      No
13       4  Dallas   Male   40  40941.0      No
14       5  Dallas   Male   46  50289.0      No

In [84]:
dataset1.loc[1]#error porque hemos modificado el index y el valor 1 ya no existe.

KeyError: 1

In [85]:
dataset1.loc[10]

Number           1
City        Dallas
Gender        Male
Age             41
Income     40367.0
Illness         No
Name: 10, dtype: object

**Slicing**

Podemos consultar rangos filas utilizando la técnica de slicing tal y como hacíamos con strings, listas y arrys.

In [86]:
dataset.loc[1:3]

   Number    City Gender  Age   Income Illness
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No

In [87]:
dataset.loc[4:]

        Number    City  Gender  Age    Income Illness
4            5  Dallas    Male   46   50289.0      No
5            6  Dallas  Female   36   50786.0      No
6            7  Dallas  Female   32   33155.0      No
7            8  Dallas    Male   39   30914.0      No
8            9  Dallas    Male   51   68667.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[149996 rows x 6 columns]

In [88]:
dataset.loc[:3]

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No

**También podemos consultar solo algunas columnas.**

In [89]:
dataset1.loc[10, 'City']#indice 10 columna City

'Dallas'

In [90]:
dataset1.loc[10, ['City', 'Age']]#indice 10 columnas City y Age

City    Dallas
Age         41
Name: 10, dtype: object

**O también es posible fijar las columnas y las filas**

In [91]:
dataset1.loc[:, ['City','Age']]#todas las filas y las columnas City y Age.

          City  Age
10      Dallas   41
11      Dallas   54
12      Dallas   42
13      Dallas   40
14      Dallas   46
...        ...  ...
150005  Austin   48
150006  Austin   25
150007  Austin   26
150008  Austin   25
150009  Austin   37

[150000 rows x 2 columns]

In [92]:
dataset1.loc[13:18, ['City','Age']]#Las filas del indice 13 al 18 y las columnas City y Age.

      City  Age
13  Dallas   40
14  Dallas   46
15  Dallas   36
16  Dallas   32
17  Dallas   39
18  Dallas   51

---
### 3. Iloc - Selección por Posición

En cambio, **<code>iloc</code>** se basa principalmente en posiciones enteras del índice (desde 0 hasta la longitud-1 del eje), pero también se puede usar con una matriz booleana. 


**<div class="alert alert-info"> Resumen función iloc </div>**

Con la función __.iloc__ podemos seleccionar varias filas de una forma muy sencilla que puede resumirse como:
* <code>dataframe.iloc[0]</code> - Primera fila de un dataframe.
* <code>dataframe.iloc[1]</code> - Segunda fila de un dataframe.
* <code>dataframe.iloc[-1]</code> - (Indexación negativa) Última fila de un dataframe
* <code>dataframe.iloc[[n]]</code> - Fila _n_ del dataframe.
* <code>dataframe.iloc[n:m]</code> - Rango personalizado de las filas _n_ a _m_

En columnas el resumen de la función __.iloc__ pasaría a ser:
* <code>dataframe.iloc[:, 0]</code> - Primera columna de un dataframe.
* <code>dataframe.iloc[:, 1]</code> - Segunda columna de un dataframe.
* <code>dataframe.iloc[:, -1]</code> - (Indexación negativa) Última columna de un dataframe
* <code>dataframe.iloc[:, [n,m]]</code> - Exactamente, las columnas _n_ y _m_ de un dataframe.
* <code>dataframe.iloc[:, n:m]</code> - Rango personalizado de las columnas _n_ a _m_ de un dataframe.

Podemos también realizar una selección múltiple de columnas filas con __.iloc__ con los siguientes ejemplos:
* <code>dataframe.iloc[[0,5,7,9], [1,4]]</code> - Selección de las filas 0,5,7,9 de las columnas 1 y 4
* <code>dataframe.iloc[0:10, 0:2]</code> - Selección basada en rangos de las filas 0 a 10 de las columnas 0 a 2

**Vamos a probar algunas de estas opciones**

In [93]:
dataset1.head()

    Number    City Gender  Age   Income Illness
10       1  Dallas   Male   41  40367.0      No
11       2  Dallas   Male   54  45084.0      No
12       3  Dallas   Male   42  52483.0      No
13       4  Dallas   Male   40  40941.0      No
14       5  Dallas   Male   46  50289.0      No

In [94]:
dataset1.iloc[:, -1]# ultima columna (illness)

10        No
11        No
12        No
13        No
14        No
          ..
150005    No
150006    No
150007    No
150008    No
150009    No
Name: Illness, Length: 150000, dtype: object

In [95]:
dataset1.iloc[0]#primera fila. Accedo por la posición que ocupa en el dataframe

Number           1
City        Dallas
Gender        Male
Age             41
Income     40367.0
Illness         No
Name: 10, dtype: object

In [96]:
#la anterior sentencia es equivalente a esta:
dataset1.loc[10]#accedo por el valor del índice.

Number           1
City        Dallas
Gender        Male
Age             41
Income     40367.0
Illness         No
Name: 10, dtype: object

Con iloc, también podemos consultar las columnas por posición

In [97]:
dataset1.iloc[0, 1]

'Dallas'

In [98]:
dataset.iloc[0, 1:3]#fila 0, columnas 1-2(la 3 no se incluye, recordarlo)

City      Dallas
Gender      Male
Name: 0, dtype: object

In [99]:
dataset1.iloc[0:10, 0:2]#Selección basada en rangos de las filas 0 a 10 de las columnas 0-1

    Number    City
10       1  Dallas
11       2  Dallas
12       3  Dallas
13       4  Dallas
14       5  Dallas
15       6  Dallas
16       7  Dallas
17       8  Dallas
18       9  Dallas
19      10  Dallas

**<div class="alert alert-info"> RECUERDA: loc accede a las filas por EL VALOR DEL INDICE  </div>**

**<div class="alert alert-info"> RECUERDA: iloc accede por la posición que ocupa la fila o columna dentro de DataFrame. </div>**

### 4 Selección de múltiples filas de un dataframe usando SLICING

Por lo general, podemos utilizar las mismas propiedades que las de las listas, salvo seleccionar una única fila que es diferente:
* Para seleccionar desde la primera fila hasta un límite realizamos: <code>__dataframe[0:n]__</code>, análogamente podemos omitir el cero y realizar simplemente: <code>__dataframe[ :n]__</code>
* Para seleccionar desde una fila hasta el final realizamos: <code>__dataframe[n:]__</code>
* Para seleccionar un rango definido de filas realizamos: <code>__dataframe[n:m]__</code>

In [100]:
dataset[0:5]

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [101]:
# Rango personalizado, escogemos de fila 150 a 200
dataset[150:200]

     Number    City  Gender  Age   Income Illness
150     151  Dallas    Male   37  60150.0      No
151     152  Dallas    Male   51  38416.0      No
152     153  Dallas  Female   54  43810.0      No
153     154  Dallas    Male   63  71551.0     Yes
154     155  Dallas  Female   36  25564.0     Yes
155     156  Dallas  Female   32  28551.0      No
156     157  Dallas    Male   48  45591.0      No
157     158  Dallas  Female   51  47559.0      No
158     159  Dallas    Male   59  53835.0      No
159     160  Dallas    Male   29  55545.0      No
160     161  Dallas  Female   27  57903.0     Yes
161     162  Dallas    Male   49  63544.0      No
162     163  Dallas  Female   54  39273.0      No
163     164  Dallas  Female   63  38841.0      No
164     165  Dallas  Female   47  48520.0      No
165     166  Dallas    Male   55  54849.0      No
166     167  Dallas    Male   45  50114.0      No
167     168  Dallas  Female   43  36894.0      No
168     169  Dallas    Male   25  42719.0      No
169     170  Dallas  Female   56  47347.0      No
170     171  Dallas  Female   54  35471.0      No
171     172  Dallas    Male   40  60636.0      No
172     173  Dallas  Female   28  48996.0      No
173     174  Dallas  Female   44  39808.0      No
174     175  Dallas    Male   47  45383.0      No
175     176  Dallas    Male   25  43413.0      No
176     177  Dallas  Female   65  50311.0      No
177     178  Dallas  Female   38  45187.0      No
178     179  Dallas    Male   54  60128.0      No
179     180  Dallas    Male   64  55066.0     Yes
180     181  Dallas  Female   38  41409.0      No
181     182  Dallas    Male   51  48899.0      No
182     183  Dallas  Female   28  32130.0      No
183     184  Dallas    Male   50  59841.0      No
184     185  Dallas    Male   47  40709.0      No
185     186  Dallas  Female   41  25012.0      No
186     187  Dallas    Male   28  40712.0      No
187     188  Dallas  Female   44  36038.0      No
188     189  Dallas  Female   56  47102.0      No
189     190  Dallas    Male   30  63365.0      No
190     191  Dallas    Male   64  22134.0      No
191     192  Dallas    Male   34  40684.0      No
192     193  Dallas    Male   52  51919.0      No
193     194  Dallas  Female   54  40526.0      No
194     195  Dallas    Male   52  48386.0      No
195     196  Dallas    Male   32  46196.0      No
196     197  Dallas    Male   51  44816.0      No
197     198  Dallas    Male   45  63285.0      No
198     199  Dallas  Female   58  19643.0      No
199     200  Dallas  Female   37  37872.0      No

Para seleccionar una sola fila no podemos hacer la misma operación que en las listas, indexar una única posición <code>lista[n]</code>, ya que esto no nos devuelve nada, para ello, tenemos que seleccionar como un rango personalizado la fila que queremos mostrar más una posición <code>dataframe[n:n+1]</code>

In [102]:
#por ejemplo queremos la fila 300
#dataset[300]# si lo ponemos así nos da error
#dataset[300:300]#así nos muestra la cabecera
dataset[300:301]

     Number    City Gender  Age   Income Illness
300     301  Dallas   Male   36  64976.0      No

---
## Lección 5 - Indexado y selección de datos - Parte II

### 1. Sample() - Recuperacion Aleatoria filas

El método sample() **recupera una selección aleatoria de filas o columnas de una serie o DataFrame.**

El método tomará muestras de filas de forma predeterminada y acepta un número específico de filas / columnas para devolver, o una fracción de filas.

In [103]:
r = dataset.sample(frac=0.01)#le indicamos que queremos un 1%
r.shape

(1500, 6)

In [104]:
dataset.sample(n=5)#queremos 5 valores aleatorios.

        Number             City  Gender  Age    Income Illness
137011  137012        San Diego    Male   56  110340.0      No
149029  149030           Austin    Male   50  111637.0      No
128110  128111  Washington D.C.  Female   45   61446.0      No
116323  116324    Mountain View    Male   34  147056.0     Yes
31695    31696    New York City    Male   50  108668.0      No

### 2. Isin() - Valores incluidos

También podemos consultar datos con la sentencia *isin*

In [105]:
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [106]:
dataset[dataset['Age'].isin([41,42])]

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
2            3  Dallas    Male   42   52483.0      No
13          14  Dallas  Female   42   50894.0      No
35          36  Dallas    Male   41   50312.0      No
37          38  Dallas  Female   41   29538.0      No
...        ...     ...     ...  ...       ...     ...
149805  149806  Austin  Female   41   71121.0      No
149839  149840  Austin    Male   41   92839.0      No
149890  149891  Austin    Male   41   87493.0      No
149923  149924  Austin  Female   42   80570.0      No
149966  149967  Austin    Male   41  105023.0      No

[7622 rows x 6 columns]

### 3. Where - Filtrando datos
La selección de valores de una serie con un vector booleano generalmente devuelve un subconjunto de los datos. 

**Para garantizar que la salida de la selección tenga la misma forma que los datos originales**, puedes utilizar el método **where** en Series y DataFrame.

**Where filtra** los valores contenidos en el dataframe de forma que **solo los que cumplan cierta condición se mantengan.** El resto de valores son **sustituidos por un valor que, por defecto, es NaN.**

In [107]:
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [108]:
#Edad == 41
dataset['Age'].where(dataset['Age'] == 41)

0         41.0
1          NaN
2          NaN
3          NaN
4          NaN
          ...
149995     NaN
149996     NaN
149997     NaN
149998     NaN
149999     NaN
Name: Age, Length: 150000, dtype: float64

In [109]:
dataset['Age'].where(dataset['Age'] == 41, -1)

0         41
1         -1
2         -1
3         -1
4         -1
          ..
149995    -1
149996    -1
149997    -1
149998    -1
149999    -1
Name: Age, Length: 150000, dtype: int64

In [110]:
#podemos también combinar filtros. Queremos los mayores de 40 y gender = Male(masculino)
filtro1 = dataset['Age'] >= 41
filtro2 = dataset['Gender'] == 'Male'
dataset.where(filtro1 & filtro2)

          Number    City Gender   Age   Income Illness
0            1.0  Dallas   Male  41.0  40367.0      No
1            2.0  Dallas   Male  54.0  45084.0      No
2            3.0  Dallas   Male  42.0  52483.0      No
3            NaN     NaN    NaN   NaN      NaN     NaN
4            5.0  Dallas   Male  46.0  50289.0      No
...          ...     ...    ...   ...      ...     ...
149995  149996.0  Austin   Male  48.0  93669.0      No
149996       NaN     NaN    NaN   NaN      NaN     NaN
149997       NaN     NaN    NaN   NaN      NaN     NaN
149998       NaN     NaN    NaN   NaN      NaN     NaN
149999       NaN     NaN    NaN   NaN      NaN     NaN

[150000 rows x 6 columns]

### 4. Query - Selección mediante expresiones

Los objetos DataFrame tienen un método query () que permite la selección mediante una expresión.

In [111]:
dataset.query('Age == 41')

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
35          36  Dallas    Male   41   50312.0      No
37          38  Dallas  Female   41   29538.0      No
41          42  Dallas    Male   41   68522.0      No
74          75  Dallas  Female   41   27897.0      No
...        ...     ...     ...  ...       ...     ...
149715  149716  Austin    Male   41   94296.0      No
149805  149806  Austin  Female   41   71121.0      No
149839  149840  Austin    Male   41   92839.0      No
149890  149891  Austin    Male   41   87493.0      No
149966  149967  Austin    Male   41  105023.0      No

[3862 rows x 6 columns]

In [112]:
dataset.query('Age == 41 | Age == 42')#registros cuya edad es 41 o 42

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
2            3  Dallas    Male   42   52483.0      No
13          14  Dallas  Female   42   50894.0      No
35          36  Dallas    Male   41   50312.0      No
37          38  Dallas  Female   41   29538.0      No
...        ...     ...     ...  ...       ...     ...
149805  149806  Austin  Female   41   71121.0      No
149839  149840  Austin    Male   41   92839.0      No
149890  149891  Austin    Male   41   87493.0      No
149923  149924  Austin  Female   42   80570.0      No
149966  149967  Austin    Male   41  105023.0      No

[7622 rows x 6 columns]

In [113]:
dataset.query('City == "Dallas" and Age != 41')#registros con ciudad Dallas y edad distinta de 41

       Number    City  Gender  Age   Income Illness
1           2  Dallas    Male   54  45084.0      No
2           3  Dallas    Male   42  52483.0      No
3           4  Dallas    Male   40  40941.0      No
4           5  Dallas    Male   46  50289.0      No
5           6  Dallas  Female   36  50786.0      No
...       ...     ...     ...  ...      ...     ...
19702   19703  Dallas  Female   59  30021.0      No
19703   19704  Dallas    Male   33  34643.0      No
19704   19705  Dallas    Male   33  53190.0      No
19705   19706  Dallas    Male   37  54265.0      No
19706   19707  Dallas    Male   59  51265.0      No

[19172 rows x 6 columns]

In [114]:
dataset.query('index < 4')

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No

In [115]:
dataset.query('Age in (41,42)')

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
2            3  Dallas    Male   42   52483.0      No
13          14  Dallas  Female   42   50894.0      No
35          36  Dallas    Male   41   50312.0      No
37          38  Dallas  Female   41   29538.0      No
...        ...     ...     ...  ...       ...     ...
149805  149806  Austin  Female   41   71121.0      No
149839  149840  Austin    Male   41   92839.0      No
149890  149891  Austin    Male   41   87493.0      No
149923  149924  Austin  Female   42   80570.0      No
149966  149967  Austin    Male   41  105023.0      No

[7622 rows x 6 columns]

**<div class="alert alert-warning">Dentro de query, podemos usar valores de variables, añadiendo al comienzo el carácter 'f'</div>**

In [116]:
ciudad_buscada = "Dallas"

dataset.query(f'City == "{ciudad_buscada}"')

       Number    City  Gender  Age   Income Illness
0           1  Dallas    Male   41  40367.0      No
1           2  Dallas    Male   54  45084.0      No
2           3  Dallas    Male   42  52483.0      No
3           4  Dallas    Male   40  40941.0      No
4           5  Dallas    Male   46  50289.0      No
...       ...     ...     ...  ...      ...     ...
19702   19703  Dallas  Female   59  30021.0      No
19703   19704  Dallas    Male   33  34643.0      No
19704   19705  Dallas    Male   33  53190.0      No
19705   19706  Dallas    Male   37  54265.0      No
19706   19707  Dallas    Male   59  51265.0      No

[19707 rows x 6 columns]

In [117]:
#podemos almacenar en una variable el texto de la query
busqueda_por_ciudad = f'City == "{ciudad_buscada}"'
dataset.query(busqueda_por_ciudad)

       Number    City  Gender  Age   Income Illness
0           1  Dallas    Male   41  40367.0      No
1           2  Dallas    Male   54  45084.0      No
2           3  Dallas    Male   42  52483.0      No
3           4  Dallas    Male   40  40941.0      No
4           5  Dallas    Male   46  50289.0      No
...       ...     ...     ...  ...      ...     ...
19702   19703  Dallas  Female   59  30021.0      No
19703   19704  Dallas    Male   33  34643.0      No
19704   19705  Dallas    Male   33  53190.0      No
19705   19706  Dallas    Male   37  54265.0      No
19706   19707  Dallas    Male   59  51265.0      No

[19707 rows x 6 columns]

### 5. Drop_duplicates - Borrado de duplicados

Si no indicamos parámetros, borra solo aquellas filas con valores duplicados en todas las columnas.

In [118]:
dataset.drop_duplicates()#borramos solo las filas con todas las columnas repetidas
#dataset.drop_duplicates('City', keep = 'first')#borramos las filas que tengan repetida el valor de la columna city y nos quedamos con la primera aparición

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

---
## Lección 6 - Multi-index

**Indice DataFrame:** Se tratan de las posiciones que ocupa cada fila dentro de un dataframe, a no ser que se especifique un tipo de índice concreto basado en etiquetas, los índices serán de 0 a la longitud total del dataframe -1.

Hasta ahora siempre hemos trabajado con un índice simple, pero pandas nos permite mantener **indices compuestos, o muli-índices.** 

Veamos como podemos generarlos.

In [119]:
import numpy as np
import pandas as pd

In [120]:
# Creamos un dataframe
ventas = {
   'Region': ["EUROPA", "EUROPA", "EUROPA", 
              "USA", "USA", "USA", "LATAM", "LATAM"],
   'Ventas':[153752, 168742, 162587, 256198, 285743, 290371, 145638, 151678],
   'Year':[2018, 2019, 2020, 2018, 2019, 2020, 2018, 2019]
}
df = pd.DataFrame(ventas)
df

   Region  Ventas  Year
0  EUROPA  153752  2018
1  EUROPA  168742  2019
2  EUROPA  162587  2020
3     USA  256198  2018
4     USA  285743  2019
5     USA  290371  2020
6   LATAM  145638  2018
7   LATAM  151678  2019

Para observar el índice de un dataframe podemos hacer uso de su atributo <code>**index**</code>

In [121]:
df.index

RangeIndex(start=0, stop=8, step=1)

Dependiendo de cómo estén formados nuestros datos, vamos a poder crear multi índices basados en columnas propias de nuestro dataframe, **si nos fijamos la columna Región y Year tienen elementos repetidos.**

**<div class="alert alert-info"> Esto nos permitirá hacer multi-índices donde tengamos un continente por año de ventas. </div>**

Con la función **<code> set_index()</code>** vamos a poder **establecer un nuevo índice.**

In [122]:
region_year = df.set_index(["Region", "Year"])
region_year

             Ventas
Region Year
EUROPA 2018  153752
       2019  168742
       2020  162587
USA    2018  256198
       2019  285743
       2020  290371
LATAM  2018  145638
       2019  151678

In [123]:
region_year.index

MultiIndex([('EUROPA', 2018),
            ('EUROPA', 2019),
            ('EUROPA', 2020),
            (   'USA', 2018),
            (   'USA', 2019),
            (   'USA', 2020),
            ( 'LATAM', 2018),
            ( 'LATAM', 2019)],
           names=['Region', 'Year'])

En vista del nuevo dataframe, podemos ver que ahora las columnas Region y Year actúan como índice, por lo que si consultamos la primera fila...

In [124]:
region_year.iloc[0]

Ventas    153752
Name: (EUROPA, 2018), dtype: int64

*Obtenemos el dato que pertenece al volumen de ventas, siendo region (Europe) y el año (2018) sus índices*

Del mismo modo, podemos pasar una lista como índice a un dataframe. Obviamente, esta lista debe ser de la misma longitud que el dataframe.

In [125]:
indice = ['REGISTRO_1', 'REGISTRO_2', 'REGISTRO_3', 'REGISTRO_4', 
          'REGISTRO_5', 'REGISTRO_6', 'REGISTRO_7', 'REGISTRO_8']

df.index = indice

df

            Region  Ventas  Year
REGISTRO_1  EUROPA  153752  2018
REGISTRO_2  EUROPA  168742  2019
REGISTRO_3  EUROPA  162587  2020
REGISTRO_4     USA  256198  2018
REGISTRO_5     USA  285743  2019
REGISTRO_6     USA  290371  2020
REGISTRO_7   LATAM  145638  2018
REGISTRO_8   LATAM  151678  2019

In [126]:
df.index

Index(['REGISTRO_1', 'REGISTRO_2', 'REGISTRO_3', 'REGISTRO_4', 'REGISTRO_5',
       'REGISTRO_6', 'REGISTRO_7', 'REGISTRO_8'],
      dtype='object')

Con la función <code>.loc</code> podemos buscar elementos en el índice

In [127]:
df.loc['REGISTRO_6']

Region       USA
Ventas    290371
Year        2020
Name: REGISTRO_6, dtype: object

**También podemos aplicar los multi-indices a las columnas de un DF**

In [128]:
from pathlib import Path
data_path = Path('./data')

Vamos a usar indices para aumentar la eficiencia de nuestras consultas

In [129]:
dataset = pd.read_csv(data_path / 'dataset.csv', sep = ',')
dataset.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [130]:
#creamos un Multi-Indice
tuples = [('Columnas_no_importantes', 'Number'),
          ('Columnas_importantes', 'City'),
          ('Columnas_no_importantes', 'Gender'),
          ('Columnas_importantes', 'Age'),
          ('Columnas_importantes', 'Income'),
          ('Columnas_no_importantes', 'Illness')
         ]

multiindex = pd.MultiIndex.from_tuples(tuples)
multiindex

MultiIndex([('Columnas_no_importantes',  'Number'),
            (   'Columnas_importantes',    'City'),
            ('Columnas_no_importantes',  'Gender'),
            (   'Columnas_importantes',     'Age'),
            (   'Columnas_importantes',  'Income'),
            ('Columnas_no_importantes', 'Illness')],
           )

In [131]:
#le pasamos el multi-indice como columnas al dataframe que hemos leido
dataset.columns = multiindex
dataset.head()

  Columnas_no_importantes Columnas_importantes Columnas_no_importantes  \
                   Number                 City                  Gender
0                       1               Dallas                    Male
1                       2               Dallas                    Male
2                       3               Dallas                    Male
3                       4               Dallas                    Male
4                       5               Dallas                    Male

  Columnas_importantes          Columnas_no_importantes
                   Age   Income                 Illness
0                   41  40367.0                      No
1                   54  45084.0                      No
2                   42  52483.0                      No
3                   40  40941.0                      No
4                   46  50289.0                      No

In [132]:
dataset['Columnas_importantes'].head()

     City  Age   Income
0  Dallas   41  40367.0
1  Dallas   54  45084.0
2  Dallas   42  52483.0
3  Dallas   40  40941.0
4  Dallas   46  50289.0

Podemos consultar los niveles de nuestro multiindex con ***levels***. También, podemos consultar los distintos niveles del índice con el método ***get_level_values(n)***

In [133]:
dataset.columns.levels

FrozenList([['Columnas_importantes', 'Columnas_no_importantes'], ['Age', 'City', 'Gender', 'Illness', 'Income', 'Number']])

In [134]:
dataset.columns.get_level_values(0)

Index(['Columnas_no_importantes', 'Columnas_importantes',
       'Columnas_no_importantes', 'Columnas_importantes',
       'Columnas_importantes', 'Columnas_no_importantes'],
      dtype='object')

In [135]:
multiindex.get_level_values(1)

Index(['Number', 'City', 'Gender', 'Age', 'Income', 'Illness'], dtype='object')

**<div class="alert alert-info">¿Cómo consulto una columna concreta? Puedo hacerlo de nuevo con .loc y una tupla </div>**

In [136]:
dataset.loc[:,('Columnas_importantes','City')]

0         Dallas
1         Dallas
2         Dallas
3         Dallas
4         Dallas
           ...
149995    Austin
149996    Austin
149997    Austin
149998    Austin
149999    Austin
Name: (Columnas_importantes, City), Length: 150000, dtype: object

Puedo hacerlo también:

In [137]:
dataset[('Columnas_importantes','City')]

0         Dallas
1         Dallas
2         Dallas
3         Dallas
4         Dallas
           ...
149995    Austin
149996    Austin
149997    Austin
149998    Austin
149999    Austin
Name: (Columnas_importantes, City), Length: 150000, dtype: object

In [138]:
dataset.loc[:,[('Columnas_importantes','City'),('Columnas_importantes','Age')]]

       Columnas_importantes
                       City Age
0                    Dallas  41
1                    Dallas  54
2                    Dallas  42
3                    Dallas  40
4                    Dallas  46
...                     ...  ..
149995               Austin  48
149996               Austin  25
149997               Austin  26
149998               Austin  25
149999               Austin  37

[150000 rows x 2 columns]

In [139]:
dataset.head()

  Columnas_no_importantes Columnas_importantes Columnas_no_importantes  \
                   Number                 City                  Gender
0                       1               Dallas                    Male
1                       2               Dallas                    Male
2                       3               Dallas                    Male
3                       4               Dallas                    Male
4                       5               Dallas                    Male

  Columnas_importantes          Columnas_no_importantes
                   Age   Income                 Illness
0                   41  40367.0                      No
1                   54  45084.0                      No
2                   42  52483.0                      No
3                   40  40941.0                      No
4                   46  50289.0                      No

Si queremos ver el indice ordenado, podemos usar la función *sort_index*.

In [140]:
dataset.sort_index(level=0, axis = 1).head()

  Columnas_importantes                  Columnas_no_importantes
                   Age    City   Income                  Gender Illness Number
0                   41  Dallas  40367.0                    Male      No      1
1                   54  Dallas  45084.0                    Male      No      2
2                   42  Dallas  52483.0                    Male      No      3
3                   40  Dallas  40941.0                    Male      No      4
4                   46  Dallas  50289.0                    Male      No      5

In [141]:
dataset.sort_index(level=1, axis = 1).head()

  Columnas_importantes         Columnas_no_importantes          \
                   Age    City                  Gender Illness
0                   41  Dallas                    Male      No
1                   54  Dallas                    Male      No
2                   42  Dallas                    Male      No
3                   40  Dallas                    Male      No
4                   46  Dallas                    Male      No

  Columnas_importantes Columnas_no_importantes
                Income                  Number
0              40367.0                       1
1              45084.0                       2
2              52483.0                       3
3              40941.0                       4
4              50289.0                       5

---
## Lección 7 - Timeseries y Timestamp

Pandas nos permite trabajar también con **series de tiempo.** Usando los tipos de datos datetime64 y timedelta64 de NumPy, pandas ha creado una enorme cantidad de nuevas funcionalidades para manipular datos de series de tiempo.

In [142]:
import pandas as pd
import numpy as np
import datetime

### 1. Timestamp y Datetime

* **El tipo de datos "Timestamp" es el tipo más básico asociado a series de tiempo. Su constructor nos permite varios inputs.**

In [143]:
ts = pd.Timestamp(2023, 1, 1)
ts

Timestamp('2023-01-01 00:00:00')

In [144]:
ts = pd.Timestamp('2023-01-01')
ts

Timestamp('2023-01-01 00:00:00')

* **Podemos crear una serie de tiempo, añadiendo varios Timestamps**

In [145]:
dt = pd.to_datetime([pd.Timestamp(2023, 1, 1), pd.Timestamp(2023, 1, 2), np.datetime64('2023-01-03'), datetime.datetime(2023, 1, 4)])
dt

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'], dtype='datetime64[ns]', freq=None)

* **También podemos crear intervalos de tiempo**

In [146]:
dt_int = pd.date_range('2023-01-01', periods=5, freq='D')
dt_int

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05'],
              dtype='datetime64[ns]', freq='D')

El parámetro freq puede tener valores:
- H: Horas
- D: Dias
- W: Semanas
- M: Meses
- Y: Años

In [147]:
dt_int = pd.date_range(start='2020-01-01', end='2020-01-10', freq='D')
dt_int

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')


**<div class="alert alert-info"> Podemos usar estas series de tiempo como indices de las series o dataframes </div>**

In [148]:
#creamos un dataframe con 10 valores entre el 0-9, con indice un rango de fechas de tipo datetime
s = pd.DataFrame(np.arange(10), index = dt_int, columns=['Valor'])
s

            Valor
2020-01-01      0
2020-01-02      1
2020-01-03      2
2020-01-04      3
2020-01-05      4
2020-01-06      5
2020-01-07      6
2020-01-08      7
2020-01-09      8
2020-01-10      9

In [149]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

* **Y podemos hacer operaciones agrupando cada X dias.**

In [150]:
s.resample('2D').mean()#agrupamos por 2 días y hacemos la media.

            Valor
2020-01-01    0.5
2020-01-03    2.5
2020-01-05    4.5
2020-01-07    6.5
2020-01-09    8.5

In [151]:
s.resample('1M').mean()#agrupamos por mes y calculamos la media

            Valor
2020-01-31    4.5

* **Para convertir otros tipos de datos a 'timestamp', podemos usar el método *to_datetime***

In [152]:
pd.to_datetime(pd.Series(['Aug 01, 2020', '2020-01-02']))

ValueError: time data "2020-01-02" doesn't match format "%b %d, %Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

* **¿Qué ocurre cuando hay una fecha "ambigua"? Por ejemplo, el "04/08/2020".** 
    
    **¿Nos referimos al 4 de Agosto o al 8 de Abril? Para ello tenemos el parámetro *day_first***

In [153]:
dia = pd.to_datetime('04/08/2020')
dia.day

8

In [154]:
dia = pd.to_datetime('04/08/2020', dayfirst=True)
dia.day

4

* **También podemos indicarlo especificando el formato exacto.**

In [155]:
df_exacto = pd.to_datetime('04/08/2020', format='%d/%m/%Y')
print(df_exacto)
df_exacto.day

2020-08-04 00:00:00

4

In [156]:
df_exacto = pd.to_datetime('04/08/2020', format='%m/%d/%Y')
print(df_exacto)
df_exacto.day

2020-04-08 00:00:00

8

**<div class="alert alert-warning">Cuando trabajamos con fechas, debemos tener especial cuidado. ¿Qué ocurre si intento crear una fecha que sea el 30 de Febrero?</div>**

In [157]:
pd.to_datetime('30/02/2020', format='%d/%m/%Y')#saltará un error por desbordar los días del mes.

ValueError: day is out of range for month, at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [158]:
pd.to_datetime('30/02/2020', format='%d/%m/%Y', errors = 'coerce')#con el parámetro errors=coerce controlamos la excepción.

NaT

NaT son las siglas de Not a Time.

---
### 2. Epoch

**Las fechas 'epoch' representan el número de segundos que han transcurrido desde el 1 de enero de 1970.** Podemos convertir ese valor en una fecha pandas.

In [160]:
pd.to_datetime([1349720105, 1349806505, 1349892905, 1349979305, 1350065705], unit='s')

DatetimeIndex(['2012-10-08 18:15:05', '2012-10-09 18:15:05',
               '2012-10-10 18:15:05', '2012-10-11 18:15:05',
               '2012-10-12 18:15:05'],
              dtype='datetime64[ns]', freq=None)

* **Hasta ahora hemos visto como generar rangos de fechas con *date_range*, pero podemos generar dichos rangos aplicando unas máscaras si usamos *bdate_range*.**

Los valores para el parámetro frecuencia podemos consultarlos [aqui](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases)

Vamos a verlo con unos ejemplos.

In [161]:
week_mask = 'Mon Tue Wed' #creamos una cadena que va a serviernos de mascara

#Generamos un rango de fechas con los lunes, martes y miercoles comprendidos entre las fechas dadas al usar nuestra mascara.
bdate_range = pd.bdate_range('2022-11-01', '2022-11-30',freq='C',  weekmask=week_mask)
bdate_range

DatetimeIndex(['2022-11-01', '2022-11-02', '2022-11-07', '2022-11-08',
               '2022-11-09', '2022-11-14', '2022-11-15', '2022-11-16',
               '2022-11-21', '2022-11-22', '2022-11-23', '2022-11-28',
               '2022-11-29', '2022-11-30'],
              dtype='datetime64[ns]', freq='C')

In [162]:
pd.to_datetime('2022-01-01').day_name()

'Saturday'

---
### 3.Componentes de los timestamp

Hay varias propiedades de fecha y hora a las que se puede acceder desde Timestamp. El listado completo podéis encontrarlo en el [siguiente enlace](https://pandas.pydata.org/docs/user_guide/timeseries.html#time-date-components).

Vamos a usar el conjunto de Timestamps que acabmos de generar.

In [163]:
week_mask = 'Mon Tue Wed'

dr = pd.bdate_range('2022-01-01', '2022-01-30', freq='C', weekmask=week_mask)
dr

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-10',
               '2022-01-11', '2022-01-12', '2022-01-17', '2022-01-18',
               '2022-01-19', '2022-01-24', '2022-01-25', '2022-01-26'],
              dtype='datetime64[ns]', freq='C')

In [164]:
# isocalendar: Separa cada componente de la fecha
ywd = dr.isocalendar()
ywd

            year  week  day
2022-01-03  2022     1    1
2022-01-04  2022     1    2
2022-01-05  2022     1    3
2022-01-10  2022     2    1
2022-01-11  2022     2    2
2022-01-12  2022     2    3
2022-01-17  2022     3    1
2022-01-18  2022     3    2
2022-01-19  2022     3    3
2022-01-24  2022     4    1
2022-01-25  2022     4    2
2022-01-26  2022     4    3

* **Podemos extraer nosotros la parte de la fecha que deseemos.**

In [165]:
dr.year

Index([2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022], dtype='int32')

In [166]:
dr.month

Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype='int32')

In [167]:
dr.day

Index([3, 4, 5, 10, 11, 12, 17, 18, 19, 24, 25, 26], dtype='int32')

In [168]:
dr.hour

Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int32')

* **También podemos extraer información de un día concreto, como el día del año que representa, el día de semana, o el nombre**

In [169]:
dr.dayofyear

Index([3, 4, 5, 10, 11, 12, 17, 18, 19, 24, 25, 26], dtype='int32')

In [170]:
dr.weekday

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype='int32')

In [171]:
dr.day_name()

Index(['Monday', 'Tuesday', 'Wednesday', 'Monday', 'Tuesday', 'Wednesday',
       'Monday', 'Tuesday', 'Wednesday', 'Monday', 'Tuesday', 'Wednesday'],
      dtype='object')

---
## Leccion 8 - Timedelta

* **Los Timedeltas son diferencias de tiempo, expresadas en unidades como días, horas, minutos, segundos.** 

* Pueden ser tanto positivos como negativos.

* Timedelta es una subclase de *datetime.timedelta* y se comporta de manera similar, pero permite la compatibilidad con los tipos np.timedelta64, así como una gran cantidad de atributos, análisis y representación personalizados.

In [172]:
import pandas as pd
import numpy as np
import datetime

In [173]:
td = pd.Timedelta('10 days')
td

Timedelta('10 days 00:00:00')

In [174]:
td = pd.Timedelta(10, unit='d')
td

Timedelta('10 days 00:00:00')

In [175]:
td = pd.Timedelta('10 days 2 hours 20 minutes')
td

Timedelta('10 days 02:20:00')

**¿Para qué nos sirven?** 
* **Nos sirven para realizar operaciones con las fechas**

In [176]:
dt_int = pd.date_range(start='2022-01-01', end='2022-03-10', freq='W')
dt_int

DatetimeIndex(['2022-01-02', '2022-01-09', '2022-01-16', '2022-01-23',
               '2022-01-30', '2022-02-06', '2022-02-13', '2022-02-20',
               '2022-02-27', '2022-03-06'],
              dtype='datetime64[ns]', freq='W-SUN')

In [177]:
dt_int + td #le sumamos 10 días, 2 horas y 20 minutos.

DatetimeIndex(['2022-01-12 02:20:00', '2022-01-19 02:20:00',
               '2022-01-26 02:20:00', '2022-02-02 02:20:00',
               '2022-02-09 02:20:00', '2022-02-16 02:20:00',
               '2022-02-23 02:20:00', '2022-03-02 02:20:00',
               '2022-03-09 02:20:00', '2022-03-16 02:20:00'],
              dtype='datetime64[ns]', freq=None)

**Vamos a crear otro rango de fechas, y vamos a restarlos, para obtener un array de timedeltas.**

In [178]:
dt_int2 = pd.date_range(start='2022-01-10', end='2022-01-19', freq='D')
dt_int2

DatetimeIndex(['2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
               '2022-01-14', '2022-01-15', '2022-01-16', '2022-01-17',
               '2022-01-18', '2022-01-19'],
              dtype='datetime64[ns]', freq='D')

In [179]:
diff = dt_int - dt_int2
diff

TimedeltaIndex(['-8 days', '-2 days',  '4 days', '10 days', '16 days',
                '22 days', '28 days', '34 days', '40 days', '46 days'],
               dtype='timedelta64[ns]', freq=None)

**Podemos preguntar por valores minimos, maximos, etc.**

In [180]:
diff.min()

Timedelta('-8 days +00:00:00')

In [181]:
diff.median()

Timedelta('19 days 00:00:00')

In [182]:
diff.max()

Timedelta('46 days 00:00:00')

**¿Como consultamos un TimeDeltaIndex?**

In [183]:
diff

TimedeltaIndex(['-8 days', '-2 days',  '4 days', '10 days', '16 days',
                '22 days', '28 days', '34 days', '40 days', '46 days'],
               dtype='timedelta64[ns]', freq=None)

In [184]:
s = pd.Series(np.arange(10), index = diff)
s

-8 days    0
-2 days    1
4 days     2
10 days    3
16 days    4
22 days    5
28 days    6
34 days    7
40 days    8
46 days    9
dtype: int32

In [185]:
s['7 days']

KeyError: Timedelta('7 days 00:00:00')

In [186]:
s['7 days':'25 days']

10 days    3
16 days    4
22 days    5
dtype: int32

---
## Lección 9. EJERCICIOS

---
### Ejercicio 1:

Lee los datos del fichero 'house.csv' en un dataframe. 

- ¿Hay alguna casa con 8 habitaciones?
- ¿Cual es el número mínimo y máximo de habitaciones en el DF?
- Crea una nueva columna que sea la relación de precio por planta. 

#### Solución:

In [ ]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Comprobamos que haya casas con 8 habitaciones
casas8Habitaciones = df[df['bedrooms'] == 8]
print(f'Número de casas con 8 habitaciones: {len(casas8Habitaciones)}')

# Obtenemos el número minimo de habitaciones
numeroMinimoHabitaciones = df['bedrooms'].min()
print(f'Número minimo de habitaciones: {numeroMinimoHabitaciones}')

#Obtenemos el número máximo de habitaciones
numeroMaximoHabitaciones = df['bedrooms'].max()
print(f'Número máximo de habitaciones: {numeroMaximoHabitaciones}')

# Creamos la nueva columna de precio por planta
df['precioPorPlanta'] = df['price']/df['floors']
# Mostramos el dataframe para ver la nueva columna
df.head()

---
### Ejercicio 2

Haciendo uso del mismo DF del ejercicio anterior calcula:
- El precio de la casa que se encuentra en la fila número 256
- El número de habitaciones de las filas 215 a 222
- Recupera una selección aleatoria del 15% del DF
- De ese 15% aleatorio, filtra aquellos registros con 3 o 4 habitaciones y precio menor a 300_000 euros

#### Solución:

In [ ]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Mostramos el precio de la casa que se encuentra en la fila 256
print(f'La casa de la fila 256 tiene un precio de: {df.iloc[256]['price']}')

# Mostramos el número de habitaciones de las casas de la fila 215 hasta la 222
print('Fila:  Número Habitaciones:')
print(df.iloc[215:223]['bedrooms'])

# Obtenemos un 15% aleatorio del dataframe
df15PorCiento = df.sample(frac=0.15)
print('DataFrame 15%: ')
print(df15PorCiento)

# Filtramos el dataframe del 15% aleatorio para obtener aquellas casa con 3 o 4 habitaciones y un precio
# por debajo de los 300000
casasFiltradas = df15PorCiento[(df15PorCiento['bedrooms'].isin([3, 4])) & (df15PorCiento['price'] < 300000)]
print('Casas Filtradas: ')
print(casasFiltradas)

---
### Ejercicio 3

Genera un índice multiple con las columnas "street", "city", "statezip" y "country" bajo el nombre "localizacion", y el resto de columnas bajo el nombre "caracteristicas". Ordena dichas columnas y genera un nuevo DF que contenga solo las columnas de "localizacion".

#### Solución:

In [ ]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Creamos el indice multiple
localizacion = ['street', 'city', 'statezip', 'country']

# Creamos una tupla que filtre todas las columnas del dataframe, si no pertenerce al indicie de localizacion, se agregan al
# indice de caracteristicas
tuplaIndices = [('localizacion', col) if col in localizacion else ('caracteristicas', col) for col in df.columns]

# Asignamos el multiindice a las columnas
df.columns = pd.MultiIndex.from_tuples(tuplaIndices)

# Ordenamos el dataframe
df = df.sort_index(axis=1)

# Creamos un nuevo dataframe con la columna de localizacion
dfLocalizacion = df['localizacion']

# Mostramos el dataframe
dfLocalizacion.head()

        city country  statezip                    street
0  Shoreline     USA  WA 98133      18810 Densmore Ave N
1    Seattle     USA  WA 98119           709 W Blaine St
2       Kent     USA  WA 98042  26206-26214 143rd Ave SE
3   Bellevue     USA  WA 98008           857 170th Pl NE
4    Redmond     USA  WA 98052         9105 170th Ave NE

---
### Ejercicio 4

Carga el fichero house.csv y realiza las siguientes operaciones:

- Convierte la columna 'date' en un tipo fecha.
- Genera 3 nuevas columnas fruto de extraer el año, mes y dia.
- ¿Cual es el precio medio por mes?
- Crea una nueva columna llamada **date2** fruto de sumar 20 días a la columna fecha.

#### Solución:

In [15]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Convertimos el campo data a tipo fecha
df['date'] = pd.to_datetime(df['date'])

# Creamos una nueva columna para año, mes y dia
df['anio'] = df['date'].dt.year
df['mes'] = df['date'].dt.month
df['dia'] = df['date'].dt.day

# Obtenemos el precio medio por mes agrupando por la columna de mes, obteniendo la media del precio
precioMedioMes = df.groupby('mes')['price'].mean().round(2)
print(f'El precio medio por mes es: {precioMedioMes}')

# Creamos la nueva columna date2 a partir de sumar 20 dias a la columna date
df['date2'] = df['date'] + pd.Timedelta(days=20)  

# Mostramos las dos columnas de fechas
df[['date', 'date2']].head()

El precio medio por mes es: mes
5    533822.84
6    547968.18
7    614407.82
Name: price, dtype: float64

        date      date2
0 2014-05-02 2014-05-22
1 2014-05-02 2014-05-22
2 2014-05-02 2014-05-22
3 2014-05-02 2014-05-22
4 2014-05-02 2014-05-22